name: Example workflow for S3 Deploy
on:
  push:
    branches: [ main ]

permissions:
  contents: read    # push가 없다면 read만; 나중에 필요 시 write로

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ← 얕은 히스토리 문제 방지

      - name: Debug git state
        run: |
          set -x
          git --version
          git branch -vv || true
          git status || true
          git log --oneline -n 5 || true
          git remote -v

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci          # 더 재현성 좋음 (package-lock.json 필요)

      - name: Build
        run: npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.bucket }}
          bucket-region: ${{ secrets.region }}
          dist-id: ${{ secrets.id }}
          invalidation: "/*"
          delete-removed: true
          no-cache: true
          private: true
